################################
# This is a basic workflow to  #
# help you get started         #
# with Github Actions testing  #
################################

name: CI

on:
  ################################
  # Triggers the workflow on     #
  # push or pull request         #
  # events on the main or master #
  # or when triggered from the   #
  # actions tab                  #
  ################################
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  workflow_dispatch:

################################
# A workflow run is made up of #
# one or more jobs that can    #
# run sequentially or in       #
# parallel                     #
################################
jobs:

  ################################
  # This workflow contains a     #
  # single job called "build"    #
  ################################
  build:

    ################################
    # The type of runner that      #
    # the job will run on          #
    ################################
    runs-on: ubuntu-latest

    ################################
    # Steps represent a sequence   #
    # of tasks that will be        #
    # executed as part of the job  #
    ################################
    steps:

      ################################
      # Checks-out your repository   #
      # under $GITHUB_WORKSPACE, so  #
      # your job can access it       #
      ################################
      - uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Layer 1 Test 1 - Lint Code Base
        uses: github/super-linter@v4
        env:
          DISABLE_ERRORS: true
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          SUPPRESS_POSSUM: true

      ################################
      # Set up your testing          #
      # environment                  #
      ################################
      - name: Install curl and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          make create-sshkey

      - name: Setup env vars and tree
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.OPENSTACK_CONFIG }}
        run: |
          echo "$SUPER_SECRET" >> ./terraform/openstack/main.tf

      ################################
      # Layer 1 syntax check         #
      ################################
      - name: Layer 1 Test 2 - make plan Terraform syntax checks
        run: make plan ENV=openstack

      # Can we check requirements, code, packages, etc for best practices?
      # ^ This can be done with Dependabot - adding to instruction document
        
      ################################
      # Run Terraform and set up     #
      # ssh config file              #
      ################################
      - name: Build Stack
        run: | 
          make auto-apply ENV=openstack        
          mkdir ~/.ssh
          cp key/id_rsa ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host django" > ~/.ssh/config 
          echo " Hostname $(make get-public-ip ENV=openstack)" | tr -d '"' >> ~/.ssh/config
          echo " User ubuntu" >> ~/.ssh/config 
          echo " IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo " StrictHostKeyChecking no"  >> ~/.ssh/config
          echo " ConnectionAttempts 5" >> ~/.ssh/config
          echo " ConnectTimeout 10" >> ~/.ssh/config
          chmod 644 ~/.ssh/config
        
 
      ################################
      # Install Inspec on            #
      # remote server                #
      ################################
      - name: Layer 2 Setup Part 1  - Install Inspec on remote host
        run: |
          ssh django bash apps/install_inspec.sh
     
      - name: Layer 2 Setup Part 2 - Finish installing Inspec
        run: | 
          ssh -o ServerAliveInterval=30 django sudo gem install inspec --no-document
          ssh -o ServerAliveInterval=30 django sudo gem install inspec-bin --no-document
          ssh django sudo ln -s /usr/share/rvm/rubies/ruby-2.7.2/bin/inspec /usr/local/bin/inspec
          ssh django sudo ln -s /usr/share/rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks /usr/local/bin/ruby_executable_hooks
          ssh django sudo inspec --chef-license=accept-silent
          ssh django git clone https://github.com/dev-sec/linux-baseline

      ################################ 
      # Layer 2 tests start          #
      ################################ 
      - name: Layer 2 Test 1 - curl polls
        run: curl -q http://$(make get-public-ip ENV=openstack | tr -d '"' )/polls/

      - name: Layer 2 Test 2 - Check running docker containers
        run: ssh django sudo docker ps

      ################################
      # Layer 2 Unit Tests contiinue # 
      # but with more Inspec!        #
      ################################
      - name: Layer 2 Test 3 - InSpect local system
        continue-on-error: true
        run: ssh django sudo inspec exec linux-baseline

      - name: Layer 2 Test 4 - InSpect sensu-backend Container
        continue-on-error: true
        run: ssh django sudo inspec exec linux-baseline -t docker://sensu-backend
        
      - name: Layer 2 Test 5 - InSpect grafana Container
        continue-on-error: true
        run: ssh django sudo inspec exec linux-baseline -t docker://grafana

      - name: Layer 2 Test 6 - InSpect app Container
        continue-on-error: true
        run: ssh django sudo inspec exec linux-baseline -t docker://app
        
      - name: Layer 2 Test 7 - InSpect nginx Container
        continue-on-error: true
        run: ssh django sudo inspec exec linux-baseline -t docker://nginx
        
      - name: Layer 2 Test 8 - InSpect Postgres Container
        continue-on-error: true
        run: ssh django sudo inspec exec linux-baseline -t docker://postgres

      ################################ 
      # Layer 3 End to End           #
      ################################ 
      - name: Layer 3 Setup - Install Terratest
        run: |
          scp -r terraform/test django:~/
          scp bin/Linux/terraform django:~/
          ssh -o ServerAliveInterval=30 django sudo apt-get install -y golang
          ssh django sudo cp ~/terraform /usr/bin/
          ssh django cd test && go mod init "TestTerraformBasicExample" && go mod tidy
      
      - name: Layer 3 Test 1 - Run Example Terratest
        run: |
          ssh django cd terraform/test && go test -v -timeout 30m

      ################################     
      # End -- Teardown environment  #
      ################################
      - name: Teardown
        if: always()
        run: make destroy ENV=openstack
